stages:
  prepare:
    cmd: python src/data/split.py
    deps:
    - data/raw_data
    - src/data/split.py
    outs:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    - data/processed_data/y_train.csv
    - data/processed_data/y_test.csv
  preprocess:
    cmd: python src/data/preprocess.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/preprocess.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/scaler.pkl
  gridsearch:
    cmd: python src/models/gridsearch.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/gridsearch.py
    outs:
    - models/best_params.pkl
  train:
    cmd: python src/models/train.py
    deps:
    - models/best_params.pkl
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/train.py
    outs:
    - models/trained_model.pkl
  evaluate:
    cmd: python src/models/evaluate.py
    deps:
    - models/trained_model.pkl
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - src/models/evaluate.py
    outs:
    - models/prediction.csv
    - metrics/scores.json
